#!/usr/bin/env bash
set -euo pipefail

WORKDIR="/home/kavia/workspace/code-generation/samsung-ott-sample-92971-93494/SamsungOTTSampleApplication"
SHPROFILE="/etc/profile.d/node_env.sh"

# Ensure workspace exists
mkdir -p "$WORKDIR"

# Verify node >=16
if ! command -v node >/dev/null; then echo "ERR: node not found" >&2; exit 10; fi
NODE_V=$(node -v 2>/dev/null || true)
NODE_MAJOR=$(echo "$NODE_V" | sed -E 's/^v([0-9]+).*/\1/' || true)
if [ -z "${NODE_MAJOR:-}" ] || [ "$NODE_MAJOR" -lt 16 ]; then echo "ERR: node >=16 required, found ${NODE_V:-unknown}" >&2; exit 11; fi

# Verify npm or yarn and versions (warn if npm <7)
if command -v npm >/dev/null; then
  NPM_V=$(npm --version 2>/dev/null || true)
  NPM_MAJOR=$(echo "$NPM_V" | cut -d. -f1 || true)
  if [ -n "${NPM_MAJOR:-}" ] && [ "$NPM_MAJOR" -lt 7 ]; then echo "WARN: npm version $NPM_V may be incompatible with some modern CRA setups" >&2; fi
elif command -v yarn >/dev/null; then
  : # yarn present
else
  echo "ERR: neither npm nor yarn found" >&2
  exit 12
fi

# Determine safe npm global bin: prefer per-user location when not root
NPM_GLOBAL_BIN=""
if [ "$(id -u)" -ne 0 ]; then
  NPM_GLOBAL_BIN="${HOME}/.npm-global/bin"
  mkdir -p "$NPM_GLOBAL_BIN"
  export PATH="$NPM_GLOBAL_BIN:$PATH"
fi

# Export NODE_ENV into current session only (default to development)
export NODE_ENV="${NODE_ENV:-development}"

# Persist minimal profile only when safe: either root or sudo non-interactive available
CAN_SUDO=1
if [ "$(id -u)" -ne 0 ]; then
  if ! sudo -n true 2>/dev/null; then CAN_SUDO=0; fi
fi
if [ "$CAN_SUDO" -eq 1 ]; then
  if [ -n "$NPM_GLOBAL_BIN" ]; then
    SHP_CONTENT="# Auto-generated by env-001 for CRA projects\nif [ -z \"\$NODE_ENV\" ]; then export NODE_ENV=development; fi\nexport PATH=\"$NPM_GLOBAL_BIN:\$PATH\"\n"
  else
    SHP_CONTENT="# Auto-generated by env-001 for CRA projects\nif [ -z \"\$NODE_ENV\" ]; then export NODE_ENV=development; fi\n"
  fi
  # read current content if exists
  if [ -f "$SHPROFILE" ]; then
    CUR=$(sudo cat "$SHPROFILE" 2>/dev/null || true)
  else
    CUR=""
  fi
  if [ "$CUR" != "$SHP_CONTENT" ]; then
    echo "$SHP_CONTENT" | sudo tee "$SHPROFILE" >/dev/null
    sudo chmod 644 "$SHPROFILE" >/dev/null || true
  fi
fi

# Final validations: ensure commands are runnable
node --version >/dev/null
if command -v npm >/dev/null; then npm --version >/dev/null; fi
if command -v yarn >/dev/null; then yarn --version >/dev/null; fi

# Print a concise success summary for logs
echo "OK: env validated (node $NODE_V, npm ${NPM_V:-installed via yarn})"
